apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: support
  template:
    metadata:
      labels:
        app: microservices
        tier: support
    spec:
        containers:
        - name: front-end
          image: hafidhuddien3/karsajobs-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
