apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: back-end
        image: hafidhuddien3/karsajobs:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: APP_PORT
            value: '8080'

          - name: MONGO_HOST
            value: mongodb

          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: MONGO_ROOT_USERNAME

          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: MONGO_ROOT_PASSWORD

# serv nam: mongodb
