apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: back-end
        image: hafidhuddien3/karsajobs:latest
        ports:
          - containerPort: 8080
        env:
          - name: nggakdipake_URL
            # Environment variable service discovery
            # Naming pattern:
            #   IP address: <all_caps_service_name>_SERVICE_HOST
            #   Port: <all_caps_service_name>_SERVICE_PORT
            #   Named Port: <all_caps_service_name>_SERVICE_PORT_<all_caps_port_name>
            value: redis://$(DATA_TIER_SERVICE_HOST):$(DATA_TIER_SERVICE_PORT_REDIS)

          - name: APP_PORT
            value: “8080”

          - name: MONGO_HOST
            value: mongodb.mongodb

          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: MONGO_ROOT_USERNAME

          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: MONGO_ROOT_PASSWORD

# serv nam: mongodb
