apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-tier
  labels:
    app: microservices
spec:
  selector:
    matchLabels:
      tier: mongo
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        tier: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo
        name: mongo
        env:
        - name: tidak dipakai
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        - name: MONGO_INITDB_ROOT_USERNAME_FILE 
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE 
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

        ports:
        - containerPort: 3306
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
        - name: mongodbsecret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim